#!/usr/bin/env python3
"""
Notion AI Automation Script
Creates AI-generated content directly in Notion using the Notion API + OpenAI
"""

import os
from notion_client import Client
from openai import OpenAI
from datetime import datetime

# Initialize clients
notion = Client(auth=os.environ.get("REFURBED_NOTION_TOKEN"))
openai_client = OpenAI(api_key=os.environ.get("REFURBED_OPENAI_API_KEY"))

def get_ai_content(prompt):
    """Generate content using OpenAI"""
    response = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=500
    )
    return response.choices[0].message.content

def list_accessible_pages():
    """List pages the integration can access"""
    print("\n📚 Searching for accessible Notion pages...")
    results = notion.search(filter={"property": "object", "value": "page"})

    pages = []
    for page in results.get("results", [])[:10]:
        title = "Untitled"
        if "properties" in page:
            for prop in page["properties"].values():
                if prop.get("type") == "title" and prop.get("title"):
                    title = prop["title"][0]["plain_text"] if prop["title"] else "Untitled"
                    break
        pages.append({"id": page["id"], "title": title})
        print(f"  - {title} ({page['id'][:8]}...)")

    return pages

def list_databases():
    """List databases the integration can access"""
    print("\n📊 Searching for accessible Notion databases...")
    # Search all and filter for databases
    results = notion.search()

    databases = []
    for item in results.get("results", []):
        if item.get("object") == "database":
            title = item.get("title", [{}])[0].get("plain_text", "Untitled") if item.get("title") else "Untitled"
            databases.append({"id": item["id"], "title": title})
            print(f"  - {title} ({item['id'][:8]}...)")

    if not databases:
        print("  (No databases found)")
    return databases

def create_ai_page(parent_page_id, topic):
    """Create a new page with AI-generated content"""
    print(f"\n🤖 Generating AI content about: {topic}")

    # Generate content with AI
    ai_content = get_ai_content(f"""Write a brief, informative article about: {topic}

    Format it with:
    - A catchy headline
    - 3-4 key points
    - A brief conclusion

    Keep it concise (under 300 words).""")

    print(f"✅ AI content generated!")

    # Create the page in Notion
    print(f"📝 Creating Notion page...")

    new_page = notion.pages.create(
        parent={"page_id": parent_page_id},
        properties={
            "title": [{"text": {"content": f"AI: {topic}"}}]
        },
        children=[
            {
                "object": "block",
                "type": "callout",
                "callout": {
                    "rich_text": [{"text": {"content": f"🤖 Generated by AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}"}}],
                    "icon": {"emoji": "🤖"}
                }
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [{"text": {"content": ai_content}}]
                }
            }
        ]
    )

    page_url = new_page.get("url", "")
    print(f"✅ Page created: {page_url}")
    return new_page

def add_ai_summary_to_database(database_id, item_title, content_to_summarize):
    """Add a new item to a database with AI-generated summary"""
    print(f"\n🤖 Generating AI summary for: {item_title}")

    summary = get_ai_content(f"Summarize this in 2-3 sentences: {content_to_summarize}")

    # Get database schema to understand properties
    db = notion.databases.retrieve(database_id)
    properties = db.get("properties", {})

    # Build page properties based on database schema
    page_props = {}
    for prop_name, prop_info in properties.items():
        if prop_info["type"] == "title":
            page_props[prop_name] = {"title": [{"text": {"content": item_title}}]}
            break

    new_page = notion.pages.create(
        parent={"database_id": database_id},
        properties=page_props,
        children=[
            {
                "object": "block",
                "type": "callout",
                "callout": {
                    "rich_text": [{"text": {"content": f"AI Summary: {summary}"}}],
                    "icon": {"emoji": "📝"}
                }
            }
        ]
    )

    print(f"✅ Database item created with AI summary!")
    return new_page

if __name__ == "__main__":
    print("=" * 60)
    print("🚀 NOTION AI AUTOMATION")
    print("=" * 60)

    # List what we can access
    pages = list_accessible_pages()
    databases = list_databases()

    if pages:
        # Create an AI-generated page under the first accessible page
        parent_id = pages[0]["id"]
        print(f"\n📄 Using parent page: {pages[0]['title']}")

        # Create AI content about a workshop topic
        topic = "AI Automation Best Practices for Business Teams"
        create_ai_page(parent_id, topic)
    else:
        print("\n⚠️ No accessible pages found. Make sure the Notion integration is connected to a page.")

    print("\n" + "=" * 60)
    print("✅ DONE!")
    print("=" * 60)
